# 基础配置
basic:
  # 下载文件保存路径
  save_dir: C:\Users\QiQi\Music\
  # 账号登录信息
  account:
    # 手机号或邮箱
    accountName: 15297923680
    # 密码
    accountPWD: YRm7PmOvlT#f5%xO!ZBA
transfer:
  URL:
    api_tracks_list: https://www.ximalaya.com/revision/album/v1/getTracksList/
    api_tracks_info: https://www.ximalaya.com/mobile-playpage/track/v3/baseInfo/
    base_album_url: https://www.ximalaya.com/album/

  headers:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
    Accept-Encoding: gzip, deflate, br, zstd
    Accept-Language: zh-CN,zh;q=0.9
    Connection: keep-alive
    Dnt: 1
    Referer: https://www.ximalaya.com/sound/638004119
    Sec-Ch-Ua: '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"'
    Sec-Ch-Ua-Mobile: ?0
    Sec-Ch-Ua-Platform: "Windows"
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: cors
    Sec-Fetch-Site: same-origin
